name: flutter_ume_kit_channel_monitor
description: channel monitor kit for flutter_ume
version: 0.0.1
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: ^1.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
